<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.upowerman</groupId>
        <artifactId>small-rpc</artifactId>
        <version>2.0.0</version>
    </parent>

    <artifactId>rpc-registry-zookeeper</artifactId>
    <name>rpc-registry-zookeeper</name>
    <description>ZooKeeper-based service registry implementation using Apache Curator for Small RPC</description>
    <url>https://github.com/upowerman/small-rpc</url>

    <dependencies>
        <dependency>
            <groupId>io.github.upowerman</groupId>
            <artifactId>rpc-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-framework</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-recipes</artifactId>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
